import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Movie Next ",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
